# Generated by Django 5.2 on 2025-04-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mk', models.CharField(max_length=10, unique=True)),
                ('nama_mk', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('tahun_akademik', models.CharField(max_length=10)),
            ],
        ),
    ]
